spring:
  application:
    name: interoperability-service
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health,info
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

