server:
  port: 8081

spring:

  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  application:
    name: api-gateway

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=0
        
        - id: observance-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/observance/**
          filters:
            - StripPrefix=0
        
        - id: telemedicine-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/telemedicine/**
          filters:
            - StripPrefix=0
        
        - id: teleexpertise-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/teleexpertise/**
          filters:
            - StripPrefix=0
        
        - id: rcp-service
          uri: http://localhost:8086
          predicates:
            - Path=/api/rcp/**
          filters:
            - StripPrefix=0
        
        - id: dcc-service
          uri: http://localhost:8087
          predicates:
            - Path=/api/dcc/**
          filters:
            - StripPrefix=0
        
        - id: transcription-service
          uri: http://localhost:8088
          predicates:
            - Path=/api/transcription/**
          filters:
            - StripPrefix=0
        
        - id: interoperability-service
          uri: http://localhost:8089
          predicates:
            - Path=/api/interoperability/**
          filters:
            - StripPrefix=0
        
        - id: security-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=0
      
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: 
              - "http://localhost:4200"
              - "http://frontend"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/nadym

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.nadym: DEBUG

---
spring:
  config:
    activate:
      on-profile: docker

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
      - org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://patient-service:8082
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=0
        
        - id: observance-service
          uri: http://observance-service:8083
          predicates:
            - Path=/api/observance/**
          filters:
            - StripPrefix=0
        
        - id: telemedicine-service
          uri: http://telemedicine-service:8084
          predicates:
            - Path=/api/telemedicine/**
          filters:
            - StripPrefix=0
        
        - id: teleexpertise-service
          uri: http://teleexpertise-service:8085
          predicates:
            - Path=/api/teleexpertise/**
          filters:
            - StripPrefix=0
        
        - id: rcp-service
          uri: http://rcp-service:8086
          predicates:
            - Path=/api/rcp/**
          filters:
            - StripPrefix=0
        
        - id: dcc-service
          uri: http://dcc-service:8087
          predicates:
            - Path=/api/dcc/**
          filters:
            - StripPrefix=0
        
        - id: transcription-service
          uri: http://transcription-service:8088
          predicates:
            - Path=/api/transcription/**
          filters:
            - StripPrefix=0
        
        - id: interoperability-service
          uri: http://interoperability-service:8089
          predicates:
            - Path=/api/interoperability/**
          filters:
            - StripPrefix=0
        
        - id: security-service
          uri: http://security-service:8090
          predicates:
            - Path=/api/security/**
          filters:
            - StripPrefix=0
  
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL}/realms/nadym